run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - bodyclose
    - durationcheck
    - makezero
    - nilerr
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    # - forcetypeassert
    - prealloc
    - deadcode
    - gosimple
    - unconvert
    - errname
    #- dupl
    - misspell

linters-settings:

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec