// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Sqlserver.proto

/*
Package SqlserverProto is a generated protocol buffer package.

It is generated from these files:
	Sqlserver.proto

It has these top-level messages:
	SplitSqlsInput
	SplitSqlsOutput
	AuditInput
	AuditOutput
	AuditResult
	GetRollbackSqlsInput
	GetRollbackSqlsOutput
*/
package SqlserverProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SplitSqlsInput struct {
	Version string `protobuf:"bytes,1,opt,name=Version" json:"Version,omitempty"`
	Sqls    string `protobuf:"bytes,2,opt,name=Sqls" json:"Sqls,omitempty"`
}

func (m *SplitSqlsInput) Reset()                    { *m = SplitSqlsInput{} }
func (m *SplitSqlsInput) String() string            { return proto.CompactTextString(m) }
func (*SplitSqlsInput) ProtoMessage()               {}
func (*SplitSqlsInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SplitSqlsInput) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SplitSqlsInput) GetSqls() string {
	if m != nil {
		return m.Sqls
	}
	return ""
}

type SplitSqlsOutput struct {
	Sqls []string `protobuf:"bytes,1,rep,name=Sqls" json:"Sqls,omitempty"`
}

func (m *SplitSqlsOutput) Reset()                    { *m = SplitSqlsOutput{} }
func (m *SplitSqlsOutput) String() string            { return proto.CompactTextString(m) }
func (*SplitSqlsOutput) ProtoMessage()               {}
func (*SplitSqlsOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SplitSqlsOutput) GetSqls() []string {
	if m != nil {
		return m.Sqls
	}
	return nil
}

type AuditInput struct {
	Version   string   `protobuf:"bytes,1,opt,name=Version" json:"Version,omitempty"`
	Sqls      []string `protobuf:"bytes,2,rep,name=Sqls" json:"Sqls,omitempty"`
	RuleNames []string `protobuf:"bytes,3,rep,name=RuleNames" json:"RuleNames,omitempty"`
}

func (m *AuditInput) Reset()                    { *m = AuditInput{} }
func (m *AuditInput) String() string            { return proto.CompactTextString(m) }
func (*AuditInput) ProtoMessage()               {}
func (*AuditInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AuditInput) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *AuditInput) GetSqls() []string {
	if m != nil {
		return m.Sqls
	}
	return nil
}

func (m *AuditInput) GetRuleNames() []string {
	if m != nil {
		return m.RuleNames
	}
	return nil
}

type AuditOutput struct {
	AuditResults []*AuditResult `protobuf:"bytes,1,rep,name=AuditResults" json:"AuditResults,omitempty"`
}

func (m *AuditOutput) Reset()                    { *m = AuditOutput{} }
func (m *AuditOutput) String() string            { return proto.CompactTextString(m) }
func (*AuditOutput) ProtoMessage()               {}
func (*AuditOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AuditOutput) GetAuditResults() []*AuditResult {
	if m != nil {
		return m.AuditResults
	}
	return nil
}

type AuditResult struct {
	AuditLevel         string `protobuf:"bytes,1,opt,name=AuditLevel" json:"AuditLevel,omitempty"`
	AuditResultMessage string `protobuf:"bytes,2,opt,name=AuditResultMessage" json:"AuditResultMessage,omitempty"`
}

func (m *AuditResult) Reset()                    { *m = AuditResult{} }
func (m *AuditResult) String() string            { return proto.CompactTextString(m) }
func (*AuditResult) ProtoMessage()               {}
func (*AuditResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AuditResult) GetAuditLevel() string {
	if m != nil {
		return m.AuditLevel
	}
	return ""
}

func (m *AuditResult) GetAuditResultMessage() string {
	if m != nil {
		return m.AuditResultMessage
	}
	return ""
}

type GetRollbackSqlsInput struct {
	Version string   `protobuf:"bytes,1,opt,name=Version" json:"Version,omitempty"`
	Sqls    []string `protobuf:"bytes,2,rep,name=Sqls" json:"Sqls,omitempty"`
}

func (m *GetRollbackSqlsInput) Reset()                    { *m = GetRollbackSqlsInput{} }
func (m *GetRollbackSqlsInput) String() string            { return proto.CompactTextString(m) }
func (*GetRollbackSqlsInput) ProtoMessage()               {}
func (*GetRollbackSqlsInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetRollbackSqlsInput) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetRollbackSqlsInput) GetSqls() []string {
	if m != nil {
		return m.Sqls
	}
	return nil
}

type GetRollbackSqlsOutput struct {
	RollbackSqls []string `protobuf:"bytes,1,rep,name=RollbackSqls" json:"RollbackSqls,omitempty"`
}

func (m *GetRollbackSqlsOutput) Reset()                    { *m = GetRollbackSqlsOutput{} }
func (m *GetRollbackSqlsOutput) String() string            { return proto.CompactTextString(m) }
func (*GetRollbackSqlsOutput) ProtoMessage()               {}
func (*GetRollbackSqlsOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetRollbackSqlsOutput) GetRollbackSqls() []string {
	if m != nil {
		return m.RollbackSqls
	}
	return nil
}

func init() {
	proto.RegisterType((*SplitSqlsInput)(nil), "SqlserverProto.SplitSqlsInput")
	proto.RegisterType((*SplitSqlsOutput)(nil), "SqlserverProto.SplitSqlsOutput")
	proto.RegisterType((*AuditInput)(nil), "SqlserverProto.AuditInput")
	proto.RegisterType((*AuditOutput)(nil), "SqlserverProto.AuditOutput")
	proto.RegisterType((*AuditResult)(nil), "SqlserverProto.AuditResult")
	proto.RegisterType((*GetRollbackSqlsInput)(nil), "SqlserverProto.GetRollbackSqlsInput")
	proto.RegisterType((*GetRollbackSqlsOutput)(nil), "SqlserverProto.GetRollbackSqlsOutput")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SqlserverService service

type SqlserverServiceClient interface {
	GetSplitSqls(ctx context.Context, in *SplitSqlsInput, opts ...grpc.CallOption) (*SplitSqlsOutput, error)
	Audit(ctx context.Context, in *AuditInput, opts ...grpc.CallOption) (*AuditOutput, error)
	GetRollbackSqls(ctx context.Context, in *GetRollbackSqlsInput, opts ...grpc.CallOption) (*GetRollbackSqlsOutput, error)
}

type sqlserverServiceClient struct {
	cc *grpc.ClientConn
}

func NewSqlserverServiceClient(cc *grpc.ClientConn) SqlserverServiceClient {
	return &sqlserverServiceClient{cc}
}

func (c *sqlserverServiceClient) GetSplitSqls(ctx context.Context, in *SplitSqlsInput, opts ...grpc.CallOption) (*SplitSqlsOutput, error) {
	out := new(SplitSqlsOutput)
	err := grpc.Invoke(ctx, "/SqlserverProto.SqlserverService/GetSplitSqls", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqlserverServiceClient) Audit(ctx context.Context, in *AuditInput, opts ...grpc.CallOption) (*AuditOutput, error) {
	out := new(AuditOutput)
	err := grpc.Invoke(ctx, "/SqlserverProto.SqlserverService/Audit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqlserverServiceClient) GetRollbackSqls(ctx context.Context, in *GetRollbackSqlsInput, opts ...grpc.CallOption) (*GetRollbackSqlsOutput, error) {
	out := new(GetRollbackSqlsOutput)
	err := grpc.Invoke(ctx, "/SqlserverProto.SqlserverService/GetRollbackSqls", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SqlserverService service

type SqlserverServiceServer interface {
	GetSplitSqls(context.Context, *SplitSqlsInput) (*SplitSqlsOutput, error)
	Audit(context.Context, *AuditInput) (*AuditOutput, error)
	GetRollbackSqls(context.Context, *GetRollbackSqlsInput) (*GetRollbackSqlsOutput, error)
}

func RegisterSqlserverServiceServer(s *grpc.Server, srv SqlserverServiceServer) {
	s.RegisterService(&_SqlserverService_serviceDesc, srv)
}

func _SqlserverService_GetSplitSqls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SplitSqlsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlserverServiceServer).GetSplitSqls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SqlserverProto.SqlserverService/GetSplitSqls",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlserverServiceServer).GetSplitSqls(ctx, req.(*SplitSqlsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _SqlserverService_Audit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlserverServiceServer).Audit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SqlserverProto.SqlserverService/Audit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlserverServiceServer).Audit(ctx, req.(*AuditInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _SqlserverService_GetRollbackSqls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRollbackSqlsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlserverServiceServer).GetRollbackSqls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SqlserverProto.SqlserverService/GetRollbackSqls",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlserverServiceServer).GetRollbackSqls(ctx, req.(*GetRollbackSqlsInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _SqlserverService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SqlserverProto.SqlserverService",
	HandlerType: (*SqlserverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSplitSqls",
			Handler:    _SqlserverService_GetSplitSqls_Handler,
		},
		{
			MethodName: "Audit",
			Handler:    _SqlserverService_Audit_Handler,
		},
		{
			MethodName: "GetRollbackSqls",
			Handler:    _SqlserverService_GetRollbackSqls_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Sqlserver.proto",
}

func init() { proto.RegisterFile("Sqlserver.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0xfd, 0xda, 0x7e, 0x2a, 0x9d, 0x96, 0x56, 0x06, 0x85, 0x10, 0xa5, 0x96, 0xc5, 0x82, 0xa7,
	0x1c, 0xea, 0x51, 0x50, 0x14, 0xa1, 0x08, 0x5a, 0x35, 0x01, 0xf1, 0x22, 0x98, 0xd6, 0x41, 0x82,
	0x6b, 0x13, 0xb3, 0x9b, 0xfc, 0x09, 0xff, 0xb4, 0x64, 0xb3, 0xd9, 0x26, 0x21, 0xa2, 0xde, 0x32,
	0x6f, 0xde, 0xbc, 0x99, 0x79, 0x93, 0x85, 0xa1, 0xf7, 0xc1, 0x05, 0xc5, 0x29, 0xc5, 0x4e, 0x14,
	0x87, 0x32, 0xc4, 0x81, 0x01, 0xee, 0xb2, 0x98, 0x9d, 0xc2, 0xc0, 0x8b, 0x78, 0x20, 0x33, 0xf8,
	0x6a, 0x15, 0x25, 0x12, 0x2d, 0xd8, 0x7a, 0xa0, 0x58, 0x04, 0xe1, 0xca, 0x6a, 0x8d, 0x5b, 0x47,
	0x5d, 0xb7, 0x08, 0x11, 0xe1, 0x7f, 0x46, 0xb3, 0xda, 0x0a, 0x56, 0xdf, 0x6c, 0x02, 0x43, 0x53,
	0x7f, 0x9b, 0xc8, 0x4c, 0xa0, 0xa0, 0xb5, 0xc6, 0x1d, 0x43, 0x7b, 0x04, 0x38, 0x4f, 0x5e, 0x02,
	0xf9, 0xfb, 0x16, 0xa6, 0x16, 0xf7, 0xa1, 0xeb, 0x26, 0x9c, 0xe6, 0xfe, 0x3b, 0x09, 0xab, 0xa3,
	0x12, 0x6b, 0x80, 0xcd, 0xa1, 0xa7, 0x94, 0x75, 0xf3, 0x33, 0xe8, 0xab, 0xd0, 0x25, 0x91, 0x70,
	0x99, 0x0f, 0xd1, 0x9b, 0xee, 0x39, 0xd5, 0xb5, 0x9d, 0x12, 0xc7, 0xad, 0x14, 0xb0, 0x27, 0xad,
	0x97, 0xc7, 0x38, 0xd2, 0x83, 0x5f, 0x53, 0x4a, 0x5c, 0x4f, 0x5b, 0x42, 0xd0, 0x01, 0x2c, 0xd1,
	0x6f, 0x48, 0x08, 0xff, 0x95, 0xb4, 0x43, 0x0d, 0x19, 0x76, 0x09, 0x3b, 0x33, 0x92, 0x6e, 0xc8,
	0xf9, 0xc2, 0x5f, 0xbe, 0xfd, 0xcd, 0xf5, 0xb5, 0x9d, 0x27, 0xb0, 0x5b, 0x53, 0xd1, 0xeb, 0x33,
	0xe8, 0x97, 0x51, 0x7d, 0x83, 0x0a, 0x36, 0xfd, 0x6c, 0xc3, 0xb6, 0xb1, 0xc3, 0xa3, 0x38, 0x0d,
	0x96, 0x84, 0xf7, 0xd0, 0x9f, 0x91, 0x34, 0xa7, 0xc4, 0x51, 0xdd, 0xb1, 0xea, 0x5f, 0x62, 0x1f,
	0x7c, 0x9b, 0xcf, 0x27, 0x61, 0xff, 0xf0, 0x02, 0x36, 0x94, 0x01, 0x68, 0x37, 0xba, 0x9f, 0xeb,
	0x34, 0x5f, 0xc6, 0x68, 0x3c, 0xc3, 0xb0, 0xb6, 0x28, 0x1e, 0xd6, 0x2b, 0x9a, 0xfc, 0xb4, 0x27,
	0x3f, 0xb0, 0x8a, 0x0e, 0x8b, 0x4d, 0xf5, 0x2e, 0x8e, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x40,
	0x9c, 0x09, 0xc5, 0x2a, 0x03, 0x00, 0x00,
}
