// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Sqlserver.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SqlserverProto {

  /// <summary>Holder for reflection information generated from Sqlserver.proto</summary>
  public static partial class SqlserverReflection {

    #region Descriptor
    /// <summary>File descriptor for Sqlserver.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SqlserverReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9TcWxzZXJ2ZXIucHJvdG8SDlNxbHNlcnZlclByb3RvIi8KDlNwbGl0U3Fs",
            "c0lucHV0Eg8KB1ZlcnNpb24YASABKAkSDAoEU3FscxgCIAEoCSIwCgNTcWwS",
            "CwoDU3FsGAEgASgJEg0KBUlzRERMGAIgASgIEg0KBUlzRE1MGAMgASgIIjkK",
            "D1NwbGl0U3Fsc091dHB1dBImCglTcGxpdFNxbHMYASADKAsyEy5TcWxzZXJ2",
            "ZXJQcm90by5TcWwiewoNU3Fsc2VydmVyTWV0YRIMCgRVc2VyGAEgASgJEhAK",
            "CFBhc3N3b3JkGAIgASgJEgwKBEhvc3QYAyABKAkSDAoEUG9ydBgEIAEoCRIX",
            "Cg9DdXJyZW50RGF0YWJhc2UYBSABKAkSFQoNQ3VycmVudFNjaGVtYRgGIAEo",
            "CSJ1CgtBZHZpc2VJbnB1dBIPCgdWZXJzaW9uGAEgASgJEgwKBFNxbHMYAiAD",
            "KAkSEQoJUnVsZU5hbWVzGAMgAygJEjQKDVNxbHNlcnZlck1ldGEYBCABKAsy",
            "HS5TcWxzZXJ2ZXJQcm90by5TcWxzZXJ2ZXJNZXRhIkMKDEFkdmlzZU91dHB1",
            "dBIzCg1BZHZpc2VSZXN1bHRzGAEgAygLMhwuU3Fsc2VydmVyUHJvdG8uQWR2",
            "aXNlUmVzdWx0IkAKDEFkdmlzZVJlc3VsdBITCgtBZHZpc2VMZXZlbBgBIAEo",
            "CRIbChNBZHZpc2VSZXN1bHRNZXNzYWdlGAIgASgJImsKFEdldFJvbGxiYWNr",
            "U3Fsc0lucHV0Eg8KB1ZlcnNpb24YASABKAkSDAoEU3FscxgCIAMoCRI0Cg1T",
            "cWxzZXJ2ZXJNZXRhGAMgASgLMh0uU3Fsc2VydmVyUHJvdG8uU3Fsc2VydmVy",
            "TWV0YSJCChVHZXRSb2xsYmFja1NxbHNPdXRwdXQSKQoMUm9sbGJhY2tTcWxz",
            "GAEgAygLMhMuU3Fsc2VydmVyUHJvdG8uU3FsMo4CChBTcWxzZXJ2ZXJTZXJ2",
            "aWNlElEKDEdldFNwbGl0U3FscxIeLlNxbHNlcnZlclByb3RvLlNwbGl0U3Fs",
            "c0lucHV0Gh8uU3Fsc2VydmVyUHJvdG8uU3BsaXRTcWxzT3V0cHV0IgASRQoG",
            "QWR2aXNlEhsuU3Fsc2VydmVyUHJvdG8uQWR2aXNlSW5wdXQaHC5TcWxzZXJ2",
            "ZXJQcm90by5BZHZpc2VPdXRwdXQiABJgCg9HZXRSb2xsYmFja1NxbHMSJC5T",
            "cWxzZXJ2ZXJQcm90by5HZXRSb2xsYmFja1NxbHNJbnB1dBolLlNxbHNlcnZl",
            "clByb3RvLkdldFJvbGxiYWNrU3Fsc091dHB1dCIAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SqlserverProto.SplitSqlsInput), global::SqlserverProto.SplitSqlsInput.Parser, new[]{ "Version", "Sqls" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SqlserverProto.Sql), global::SqlserverProto.Sql.Parser, new[]{ "Sql_", "IsDDL", "IsDML" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SqlserverProto.SplitSqlsOutput), global::SqlserverProto.SplitSqlsOutput.Parser, new[]{ "SplitSqls" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SqlserverProto.SqlserverMeta), global::SqlserverProto.SqlserverMeta.Parser, new[]{ "User", "Password", "Host", "Port", "CurrentDatabase", "CurrentSchema" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SqlserverProto.AdviseInput), global::SqlserverProto.AdviseInput.Parser, new[]{ "Version", "Sqls", "RuleNames", "SqlserverMeta" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SqlserverProto.AdviseOutput), global::SqlserverProto.AdviseOutput.Parser, new[]{ "AdviseResults" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SqlserverProto.AdviseResult), global::SqlserverProto.AdviseResult.Parser, new[]{ "AdviseLevel", "AdviseResultMessage" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SqlserverProto.GetRollbackSqlsInput), global::SqlserverProto.GetRollbackSqlsInput.Parser, new[]{ "Version", "Sqls", "SqlserverMeta" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SqlserverProto.GetRollbackSqlsOutput), global::SqlserverProto.GetRollbackSqlsOutput.Parser, new[]{ "RollbackSqls" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SplitSqlsInput : pb::IMessage<SplitSqlsInput> {
    private static readonly pb::MessageParser<SplitSqlsInput> _parser = new pb::MessageParser<SplitSqlsInput>(() => new SplitSqlsInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SplitSqlsInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SqlserverProto.SqlserverReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SplitSqlsInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SplitSqlsInput(SplitSqlsInput other) : this() {
      version_ = other.version_;
      sqls_ = other.sqls_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SplitSqlsInput Clone() {
      return new SplitSqlsInput(this);
    }

    /// <summary>Field number for the "Version" field.</summary>
    public const int VersionFieldNumber = 1;
    private string version_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Version {
      get { return version_; }
      set {
        version_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Sqls" field.</summary>
    public const int SqlsFieldNumber = 2;
    private string sqls_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Sqls {
      get { return sqls_; }
      set {
        sqls_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SplitSqlsInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SplitSqlsInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Version != other.Version) return false;
      if (Sqls != other.Sqls) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Version.Length != 0) hash ^= Version.GetHashCode();
      if (Sqls.Length != 0) hash ^= Sqls.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Version.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Version);
      }
      if (Sqls.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Sqls);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Version.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Version);
      }
      if (Sqls.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sqls);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SplitSqlsInput other) {
      if (other == null) {
        return;
      }
      if (other.Version.Length != 0) {
        Version = other.Version;
      }
      if (other.Sqls.Length != 0) {
        Sqls = other.Sqls;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Version = input.ReadString();
            break;
          }
          case 18: {
            Sqls = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Sql : pb::IMessage<Sql> {
    private static readonly pb::MessageParser<Sql> _parser = new pb::MessageParser<Sql>(() => new Sql());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Sql> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SqlserverProto.SqlserverReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Sql() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Sql(Sql other) : this() {
      sql_ = other.sql_;
      isDDL_ = other.isDDL_;
      isDML_ = other.isDML_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Sql Clone() {
      return new Sql(this);
    }

    /// <summary>Field number for the "Sql" field.</summary>
    public const int Sql_FieldNumber = 1;
    private string sql_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Sql_ {
      get { return sql_; }
      set {
        sql_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IsDDL" field.</summary>
    public const int IsDDLFieldNumber = 2;
    private bool isDDL_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsDDL {
      get { return isDDL_; }
      set {
        isDDL_ = value;
      }
    }

    /// <summary>Field number for the "IsDML" field.</summary>
    public const int IsDMLFieldNumber = 3;
    private bool isDML_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsDML {
      get { return isDML_; }
      set {
        isDML_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Sql);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Sql other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Sql_ != other.Sql_) return false;
      if (IsDDL != other.IsDDL) return false;
      if (IsDML != other.IsDML) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Sql_.Length != 0) hash ^= Sql_.GetHashCode();
      if (IsDDL != false) hash ^= IsDDL.GetHashCode();
      if (IsDML != false) hash ^= IsDML.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Sql_.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Sql_);
      }
      if (IsDDL != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsDDL);
      }
      if (IsDML != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsDML);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Sql_.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sql_);
      }
      if (IsDDL != false) {
        size += 1 + 1;
      }
      if (IsDML != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Sql other) {
      if (other == null) {
        return;
      }
      if (other.Sql_.Length != 0) {
        Sql_ = other.Sql_;
      }
      if (other.IsDDL != false) {
        IsDDL = other.IsDDL;
      }
      if (other.IsDML != false) {
        IsDML = other.IsDML;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Sql_ = input.ReadString();
            break;
          }
          case 16: {
            IsDDL = input.ReadBool();
            break;
          }
          case 24: {
            IsDML = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SplitSqlsOutput : pb::IMessage<SplitSqlsOutput> {
    private static readonly pb::MessageParser<SplitSqlsOutput> _parser = new pb::MessageParser<SplitSqlsOutput>(() => new SplitSqlsOutput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SplitSqlsOutput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SqlserverProto.SqlserverReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SplitSqlsOutput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SplitSqlsOutput(SplitSqlsOutput other) : this() {
      splitSqls_ = other.splitSqls_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SplitSqlsOutput Clone() {
      return new SplitSqlsOutput(this);
    }

    /// <summary>Field number for the "SplitSqls" field.</summary>
    public const int SplitSqlsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::SqlserverProto.Sql> _repeated_splitSqls_codec
        = pb::FieldCodec.ForMessage(10, global::SqlserverProto.Sql.Parser);
    private readonly pbc::RepeatedField<global::SqlserverProto.Sql> splitSqls_ = new pbc::RepeatedField<global::SqlserverProto.Sql>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::SqlserverProto.Sql> SplitSqls {
      get { return splitSqls_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SplitSqlsOutput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SplitSqlsOutput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!splitSqls_.Equals(other.splitSqls_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= splitSqls_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      splitSqls_.WriteTo(output, _repeated_splitSqls_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += splitSqls_.CalculateSize(_repeated_splitSqls_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SplitSqlsOutput other) {
      if (other == null) {
        return;
      }
      splitSqls_.Add(other.splitSqls_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            splitSqls_.AddEntriesFrom(input, _repeated_splitSqls_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class SqlserverMeta : pb::IMessage<SqlserverMeta> {
    private static readonly pb::MessageParser<SqlserverMeta> _parser = new pb::MessageParser<SqlserverMeta>(() => new SqlserverMeta());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SqlserverMeta> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SqlserverProto.SqlserverReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SqlserverMeta() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SqlserverMeta(SqlserverMeta other) : this() {
      user_ = other.user_;
      password_ = other.password_;
      host_ = other.host_;
      port_ = other.port_;
      currentDatabase_ = other.currentDatabase_;
      currentSchema_ = other.currentSchema_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SqlserverMeta Clone() {
      return new SqlserverMeta(this);
    }

    /// <summary>Field number for the "User" field.</summary>
    public const int UserFieldNumber = 1;
    private string user_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string User {
      get { return user_; }
      set {
        user_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Host" field.</summary>
    public const int HostFieldNumber = 3;
    private string host_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Host {
      get { return host_; }
      set {
        host_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Port" field.</summary>
    public const int PortFieldNumber = 4;
    private string port_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Port {
      get { return port_; }
      set {
        port_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CurrentDatabase" field.</summary>
    public const int CurrentDatabaseFieldNumber = 5;
    private string currentDatabase_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CurrentDatabase {
      get { return currentDatabase_; }
      set {
        currentDatabase_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CurrentSchema" field.</summary>
    public const int CurrentSchemaFieldNumber = 6;
    private string currentSchema_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CurrentSchema {
      get { return currentSchema_; }
      set {
        currentSchema_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SqlserverMeta);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SqlserverMeta other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (User != other.User) return false;
      if (Password != other.Password) return false;
      if (Host != other.Host) return false;
      if (Port != other.Port) return false;
      if (CurrentDatabase != other.CurrentDatabase) return false;
      if (CurrentSchema != other.CurrentSchema) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (User.Length != 0) hash ^= User.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (Host.Length != 0) hash ^= Host.GetHashCode();
      if (Port.Length != 0) hash ^= Port.GetHashCode();
      if (CurrentDatabase.Length != 0) hash ^= CurrentDatabase.GetHashCode();
      if (CurrentSchema.Length != 0) hash ^= CurrentSchema.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (User.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(User);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (Host.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Host);
      }
      if (Port.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Port);
      }
      if (CurrentDatabase.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(CurrentDatabase);
      }
      if (CurrentSchema.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(CurrentSchema);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (User.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(User);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (Host.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Host);
      }
      if (Port.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Port);
      }
      if (CurrentDatabase.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CurrentDatabase);
      }
      if (CurrentSchema.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CurrentSchema);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SqlserverMeta other) {
      if (other == null) {
        return;
      }
      if (other.User.Length != 0) {
        User = other.User;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      if (other.Host.Length != 0) {
        Host = other.Host;
      }
      if (other.Port.Length != 0) {
        Port = other.Port;
      }
      if (other.CurrentDatabase.Length != 0) {
        CurrentDatabase = other.CurrentDatabase;
      }
      if (other.CurrentSchema.Length != 0) {
        CurrentSchema = other.CurrentSchema;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            User = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
          case 26: {
            Host = input.ReadString();
            break;
          }
          case 34: {
            Port = input.ReadString();
            break;
          }
          case 42: {
            CurrentDatabase = input.ReadString();
            break;
          }
          case 50: {
            CurrentSchema = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class AdviseInput : pb::IMessage<AdviseInput> {
    private static readonly pb::MessageParser<AdviseInput> _parser = new pb::MessageParser<AdviseInput>(() => new AdviseInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AdviseInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SqlserverProto.SqlserverReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AdviseInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AdviseInput(AdviseInput other) : this() {
      version_ = other.version_;
      sqls_ = other.sqls_.Clone();
      ruleNames_ = other.ruleNames_.Clone();
      sqlserverMeta_ = other.sqlserverMeta_ != null ? other.sqlserverMeta_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AdviseInput Clone() {
      return new AdviseInput(this);
    }

    /// <summary>Field number for the "Version" field.</summary>
    public const int VersionFieldNumber = 1;
    private string version_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Version {
      get { return version_; }
      set {
        version_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Sqls" field.</summary>
    public const int SqlsFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_sqls_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> sqls_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Sqls {
      get { return sqls_; }
    }

    /// <summary>Field number for the "RuleNames" field.</summary>
    public const int RuleNamesFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_ruleNames_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> ruleNames_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> RuleNames {
      get { return ruleNames_; }
    }

    /// <summary>Field number for the "SqlserverMeta" field.</summary>
    public const int SqlserverMetaFieldNumber = 4;
    private global::SqlserverProto.SqlserverMeta sqlserverMeta_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SqlserverProto.SqlserverMeta SqlserverMeta {
      get { return sqlserverMeta_; }
      set {
        sqlserverMeta_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AdviseInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AdviseInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Version != other.Version) return false;
      if(!sqls_.Equals(other.sqls_)) return false;
      if(!ruleNames_.Equals(other.ruleNames_)) return false;
      if (!object.Equals(SqlserverMeta, other.SqlserverMeta)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Version.Length != 0) hash ^= Version.GetHashCode();
      hash ^= sqls_.GetHashCode();
      hash ^= ruleNames_.GetHashCode();
      if (sqlserverMeta_ != null) hash ^= SqlserverMeta.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Version.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Version);
      }
      sqls_.WriteTo(output, _repeated_sqls_codec);
      ruleNames_.WriteTo(output, _repeated_ruleNames_codec);
      if (sqlserverMeta_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(SqlserverMeta);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Version.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Version);
      }
      size += sqls_.CalculateSize(_repeated_sqls_codec);
      size += ruleNames_.CalculateSize(_repeated_ruleNames_codec);
      if (sqlserverMeta_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SqlserverMeta);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AdviseInput other) {
      if (other == null) {
        return;
      }
      if (other.Version.Length != 0) {
        Version = other.Version;
      }
      sqls_.Add(other.sqls_);
      ruleNames_.Add(other.ruleNames_);
      if (other.sqlserverMeta_ != null) {
        if (sqlserverMeta_ == null) {
          sqlserverMeta_ = new global::SqlserverProto.SqlserverMeta();
        }
        SqlserverMeta.MergeFrom(other.SqlserverMeta);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Version = input.ReadString();
            break;
          }
          case 18: {
            sqls_.AddEntriesFrom(input, _repeated_sqls_codec);
            break;
          }
          case 26: {
            ruleNames_.AddEntriesFrom(input, _repeated_ruleNames_codec);
            break;
          }
          case 34: {
            if (sqlserverMeta_ == null) {
              sqlserverMeta_ = new global::SqlserverProto.SqlserverMeta();
            }
            input.ReadMessage(sqlserverMeta_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class AdviseOutput : pb::IMessage<AdviseOutput> {
    private static readonly pb::MessageParser<AdviseOutput> _parser = new pb::MessageParser<AdviseOutput>(() => new AdviseOutput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AdviseOutput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SqlserverProto.SqlserverReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AdviseOutput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AdviseOutput(AdviseOutput other) : this() {
      adviseResults_ = other.adviseResults_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AdviseOutput Clone() {
      return new AdviseOutput(this);
    }

    /// <summary>Field number for the "AdviseResults" field.</summary>
    public const int AdviseResultsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::SqlserverProto.AdviseResult> _repeated_adviseResults_codec
        = pb::FieldCodec.ForMessage(10, global::SqlserverProto.AdviseResult.Parser);
    private readonly pbc::RepeatedField<global::SqlserverProto.AdviseResult> adviseResults_ = new pbc::RepeatedField<global::SqlserverProto.AdviseResult>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::SqlserverProto.AdviseResult> AdviseResults {
      get { return adviseResults_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AdviseOutput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AdviseOutput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!adviseResults_.Equals(other.adviseResults_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= adviseResults_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      adviseResults_.WriteTo(output, _repeated_adviseResults_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += adviseResults_.CalculateSize(_repeated_adviseResults_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AdviseOutput other) {
      if (other == null) {
        return;
      }
      adviseResults_.Add(other.adviseResults_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            adviseResults_.AddEntriesFrom(input, _repeated_adviseResults_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class AdviseResult : pb::IMessage<AdviseResult> {
    private static readonly pb::MessageParser<AdviseResult> _parser = new pb::MessageParser<AdviseResult>(() => new AdviseResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AdviseResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SqlserverProto.SqlserverReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AdviseResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AdviseResult(AdviseResult other) : this() {
      adviseLevel_ = other.adviseLevel_;
      adviseResultMessage_ = other.adviseResultMessage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AdviseResult Clone() {
      return new AdviseResult(this);
    }

    /// <summary>Field number for the "AdviseLevel" field.</summary>
    public const int AdviseLevelFieldNumber = 1;
    private string adviseLevel_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AdviseLevel {
      get { return adviseLevel_; }
      set {
        adviseLevel_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "AdviseResultMessage" field.</summary>
    public const int AdviseResultMessageFieldNumber = 2;
    private string adviseResultMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AdviseResultMessage {
      get { return adviseResultMessage_; }
      set {
        adviseResultMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AdviseResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AdviseResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AdviseLevel != other.AdviseLevel) return false;
      if (AdviseResultMessage != other.AdviseResultMessage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AdviseLevel.Length != 0) hash ^= AdviseLevel.GetHashCode();
      if (AdviseResultMessage.Length != 0) hash ^= AdviseResultMessage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AdviseLevel.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AdviseLevel);
      }
      if (AdviseResultMessage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AdviseResultMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AdviseLevel.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AdviseLevel);
      }
      if (AdviseResultMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AdviseResultMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AdviseResult other) {
      if (other == null) {
        return;
      }
      if (other.AdviseLevel.Length != 0) {
        AdviseLevel = other.AdviseLevel;
      }
      if (other.AdviseResultMessage.Length != 0) {
        AdviseResultMessage = other.AdviseResultMessage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AdviseLevel = input.ReadString();
            break;
          }
          case 18: {
            AdviseResultMessage = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetRollbackSqlsInput : pb::IMessage<GetRollbackSqlsInput> {
    private static readonly pb::MessageParser<GetRollbackSqlsInput> _parser = new pb::MessageParser<GetRollbackSqlsInput>(() => new GetRollbackSqlsInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetRollbackSqlsInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SqlserverProto.SqlserverReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRollbackSqlsInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRollbackSqlsInput(GetRollbackSqlsInput other) : this() {
      version_ = other.version_;
      sqls_ = other.sqls_.Clone();
      sqlserverMeta_ = other.sqlserverMeta_ != null ? other.sqlserverMeta_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRollbackSqlsInput Clone() {
      return new GetRollbackSqlsInput(this);
    }

    /// <summary>Field number for the "Version" field.</summary>
    public const int VersionFieldNumber = 1;
    private string version_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Version {
      get { return version_; }
      set {
        version_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Sqls" field.</summary>
    public const int SqlsFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_sqls_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> sqls_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Sqls {
      get { return sqls_; }
    }

    /// <summary>Field number for the "SqlserverMeta" field.</summary>
    public const int SqlserverMetaFieldNumber = 3;
    private global::SqlserverProto.SqlserverMeta sqlserverMeta_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SqlserverProto.SqlserverMeta SqlserverMeta {
      get { return sqlserverMeta_; }
      set {
        sqlserverMeta_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetRollbackSqlsInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetRollbackSqlsInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Version != other.Version) return false;
      if(!sqls_.Equals(other.sqls_)) return false;
      if (!object.Equals(SqlserverMeta, other.SqlserverMeta)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Version.Length != 0) hash ^= Version.GetHashCode();
      hash ^= sqls_.GetHashCode();
      if (sqlserverMeta_ != null) hash ^= SqlserverMeta.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Version.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Version);
      }
      sqls_.WriteTo(output, _repeated_sqls_codec);
      if (sqlserverMeta_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(SqlserverMeta);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Version.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Version);
      }
      size += sqls_.CalculateSize(_repeated_sqls_codec);
      if (sqlserverMeta_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SqlserverMeta);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetRollbackSqlsInput other) {
      if (other == null) {
        return;
      }
      if (other.Version.Length != 0) {
        Version = other.Version;
      }
      sqls_.Add(other.sqls_);
      if (other.sqlserverMeta_ != null) {
        if (sqlserverMeta_ == null) {
          sqlserverMeta_ = new global::SqlserverProto.SqlserverMeta();
        }
        SqlserverMeta.MergeFrom(other.SqlserverMeta);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Version = input.ReadString();
            break;
          }
          case 18: {
            sqls_.AddEntriesFrom(input, _repeated_sqls_codec);
            break;
          }
          case 26: {
            if (sqlserverMeta_ == null) {
              sqlserverMeta_ = new global::SqlserverProto.SqlserverMeta();
            }
            input.ReadMessage(sqlserverMeta_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetRollbackSqlsOutput : pb::IMessage<GetRollbackSqlsOutput> {
    private static readonly pb::MessageParser<GetRollbackSqlsOutput> _parser = new pb::MessageParser<GetRollbackSqlsOutput>(() => new GetRollbackSqlsOutput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetRollbackSqlsOutput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SqlserverProto.SqlserverReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRollbackSqlsOutput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRollbackSqlsOutput(GetRollbackSqlsOutput other) : this() {
      rollbackSqls_ = other.rollbackSqls_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRollbackSqlsOutput Clone() {
      return new GetRollbackSqlsOutput(this);
    }

    /// <summary>Field number for the "RollbackSqls" field.</summary>
    public const int RollbackSqlsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::SqlserverProto.Sql> _repeated_rollbackSqls_codec
        = pb::FieldCodec.ForMessage(10, global::SqlserverProto.Sql.Parser);
    private readonly pbc::RepeatedField<global::SqlserverProto.Sql> rollbackSqls_ = new pbc::RepeatedField<global::SqlserverProto.Sql>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::SqlserverProto.Sql> RollbackSqls {
      get { return rollbackSqls_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetRollbackSqlsOutput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetRollbackSqlsOutput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!rollbackSqls_.Equals(other.rollbackSqls_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= rollbackSqls_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      rollbackSqls_.WriteTo(output, _repeated_rollbackSqls_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += rollbackSqls_.CalculateSize(_repeated_rollbackSqls_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetRollbackSqlsOutput other) {
      if (other == null) {
        return;
      }
      rollbackSqls_.Add(other.rollbackSqls_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            rollbackSqls_.AddEntriesFrom(input, _repeated_rollbackSqls_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
