name: CI (no build)

on:
  pull_request:
    branches:
      - 'main*'
      - 'release*'
      
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # Should be consistent with go.mod
          go-version: '1.19.6'

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.45.2
          args: --config=.golangci.yml

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # Should be consistent with go.mod
          go-version: '1.19.6'
      - name: Unit test
        run: make test