on:
  pull_request:
    branches:
      - release*
    types: ["closed"]

jobs:
  cherry_pick_release_2_main:
    if: contains(github.event.pull_request.labels.*.name, 'need_cherry_pick')
    runs-on: ubuntu-latest
    name: Cherry pick into main
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Create PR to main
      uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
      with:
        branch: ${{ github.repository == 'actiontech/sqle-ee' && 'main-ee' || 'main' }}
        labels: |
          cherry-pick