on:
  pull_request:
    branches:
      - release*
    types: ["closed"]

jobs:
  cherry_pick_release_2_main:
    if: github.event.pull_request.merged == true && github.repository == 'actiontech/sqle'
    runs-on: ubuntu-latest
    name: Cherry pick into main
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into main
        uses: Nathanmalnoury/gh-backport-action@master
        with:
          pr_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}