name: Trigger sqle-ee Workflow

on:
  push:
    branches:
      - main
      - 'release*'

jobs:
  trigger-sync-workflow:
    # this file will sync to sqle-ee, we only execute job on actiontech/sqle
    if: github.repository == 'actiontech/sqle' 
    name: Create workflow dispatch on sqle-ee
    runs-on: ubuntu-latest
    steps:
      - name: Trigger sqle-ee workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.DOWNSTREAM_REPO_SECRET }}
          repo: actiontech/sqle-ee
          workflow: Sync with SQLE
          ref: ${{ github.ref }}-ee